[colors.primary]
background = '#04293a'
foreground = '#f2f3f3'
 
[colors.cursor]
text = '#f2f3f3'
cursor = '#afb5b6' 
 
[colors.vi_mode_cursor]
text = '#04293a'
cursor = '#57dff5' 
 
[colors.search.matches]
foreground = '#083649' 
background = '#573ff3' 
 
[colors.search.focused_match]
foreground = '#083649' 
background = '#57dff5' 
 
[colors.footer_bar]
foreground = '#083649' 
background = '#e3e7e8' 
 
[colors.hints.start]
foreground = '#083649' 
background = '#3f7bf3' 
 
[colors.hints.end]
foreground = '#083649' 
background = '#3f7bf3' 
 
[colors.selection]
text = '#04293a'
background = '#57dff5'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#57dff5' 
yellow = '#1e9bae' 
blue = '#57dff5' 
magenta = '#573ff3' 
cyan = '#3f7bf3' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 