[colors.primary]
background = '#000000'
foreground = '#f0ebe6'

[colors.cursor]
text = '#000000'
cursor = '#f58888'

[colors.vi_mode_cursor]
text = '#1a1a1a'
cursor = '#d06666'

[colors.search.matches]
foreground = '#080808'
background = '#f0e68c'

[colors.search.focused_match]
foreground = '#080808'
background = '#d06666'

[colors.footer_bar]
foreground = '#080808'
background = '#e8e3e3'

[colors.hints.start]
foreground = '#080808'
background = '#ffa247'

[colors.hints.end]
foreground = '#080808'
background = '#ffa247'

[colors.selection]
text = '#f0ebe6'
background = '#5a3824'


[colors.normal]
black   = '#000000'
red     = '#d06666'
green   = '#53d390'
yellow  = '#f0e68c'
blue    = '#519bff'
magenta = '#c28eff'
cyan    = '#5abaae'
white   = '#dddbd5'


[colors.bright]
black   = '#666666'
red     = '#ffa0a0'
green   = '#96ea7f'
yellow  = '#ffa247'
blue    = '#87ceeb'
magenta = '#d2adff'
cyan    = '#8fd1c7'
white   = '#fff9f2'


[colors.dim]
black   = '#000000'
red     = '#d06666'
green   = '#53d390'
yellow  = '#f0e68c'
blue    = '#519bff'
magenta = '#c28eff'
cyan    = '#5abaae'
white   = '#dddbd5'
