[colors.primary]
background = '#121318'
foreground = '#e3e2e9'

[colors.cursor]
text = '#121318'
cursor = '#e3e2e9'

[colors.vi_mode_cursor]
text = '#121318'
cursor = '#b3c5ff'

[colors.search.matches]
foreground = '#444651'
background = '#fcabfb'

[colors.search.focused_match]
foreground = '#444651'
background = '#b3c5ff'

[colors.footer_bar]
foreground = '#444651'
background = '#e3e2e9'

[colors.hints.start]
foreground = '#444651'
background = '#bbc5ec'

[colors.hints.end]
foreground = '#444651'
background = '#bbc5ec'

[colors.selection]
text = '#c4c6d3'
background = '#444651'


[colors.normal]
black   = '#444651'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#bbc5ec'
blue    = '#fcabfb'
magenta = '#b3c5ff'
cyan    = '#bbc5ec'
white   = '#e3e2e9'


[colors.bright]
black   = '#8e909d'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#bbc5ec'
blue    = '#fcabfb'
magenta = '#b3c5ff'
cyan    = '#bbc5ec'
white   = '#e3e2e9'


[colors.dim]
black   = '#444651'
red     = '#ffb4ab'
green   = '#b3c5ff'
yellow  = '#bbc5ec'
blue    = '#fcabfb'
magenta = '#b3c5ff'
cyan    = '#bbc5ec'
white   = '#e3e2e9'
