[bar.default]
background_opacity = 0.5
center = [ "date", "spacer_2", "clock" ]
end = [
    "weather",
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "headphone_batt",
    "session"
]
margin_edge = 8
scale = 1.350000012665987
start = [ "launcher", "wallpaper", "workspaces", "cpu_usage", "cpu_temp", "memory" ]

    [bar.default.monitor.DP-1]
    enabled = false

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 30

[brightness]
enable_ddcutil = true

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@DP-5" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    cx = 720.0
    cy = 2437.0
    output = "DP-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    cx = 1280.0
    cy = 1317.0
    output = "DP-5"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

[shell]
corner_radius_scale = 1.3500000201165676
font_family = "Inter"
polkit_agent = true
telemetry_enabled = false
ui_scale = 1.2500000111758709

    [shell.panel]
    session_placement = "centered"

    [shell.shadow]
    direction = "down_right"

[theme]
builtin = "Ayu"
community_palette = "Oasis Abyss"
custom_palette = "Ayu"
mode = "dark"
source = "community"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "zathura" ]

[wallpaper]
directory = "/home/browser/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.last]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.monitors.DP-1]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.monitors.DP-5]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [[wallpaper.favorite]]
    community_palette = "Oasis Abyss"
    palette_source = "community"
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"
    theme_mode = "dark"

[widget.batt_headphones]
device = "/org/freedesktop/UPower/devices/headset_dev_AC_80_0A_AE_7D_10"
display_mode = "graphic"
type = "battery"

[widget.battery]
device = "/org/freedesktop/UPower/devices/battery_hidpp_battery_0"
display_mode = "graphic"
hide_when_full = true
hide_when_plugged = true

[widget.clock]
anchor = true
color = "on_surface_variant"

[widget.cpu_temp]
gauge_color = "secondary"
stat = "cpu_temp"
type = "sysmon"

[widget.cpu_usage]
type = "sysmon"

[widget.date]
color = "on_surface_variant"

[widget.gpu_temp]
stat = "gpu_temp"
type = "sysmon"

[widget.gpu_usage]
stat = "gpu_usage"
type = "sysmon"

[widget.headphone_batt]
device = "/org/freedesktop/UPower/devices/headset_dev_AC_80_0A_AE_7D_10"
display_mode = "graphic"
type = "battery"

[widget.media]
hide_when_no_media = true

[widget.memory]
stat = "ram_used"
type = "sysmon"

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"