config_version = 14

[accessibility]
ui_scale = 1.2500000111758709

[bar.default]
background_opacity = 0.5
center = [ "date", "spacer_2", "clock" ]
end = [
    "weather",
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "headphone_batt",
    "session"
]
margin_edge = 8
scale = 1.350000012665987
start = [ "launcher", "wallpaper", "workspaces", "cpu_usage", "cpu_temp", "memory", "hello" ]

    [bar.default.monitor.DP-1]
    enabled = false

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 30

[brightness]
enable_ddcutil = true

[lockscreen_widgets]
enabled = false
schema_version = 1
widget_order = [
    "lockscreen-login-box@HDMI-A-5",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-4",
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@DP-5"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 720.0
    cy = 2437.0
    output = "DP-1"
    placement_height = 2560.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-3"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-4"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-5"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1317.0
    output = "DP-5"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-5".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-5"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-5"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-5".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugin_settings."me/example"]
greeter_open_near_click = true
greeter_placement = "attached"

[plugin_settings."noctalia/timer"]
panel_placement = "floating"
panel_position = "center"

[plugins]
auto_update = "all"
enabled = [ "me/icue-presets" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "~/noctalia/plugins/"
    name = "my-plugins"

[shell]
font_family = "Inter"
polkit_agent = true
telemetry_enabled = false
ui_scale = 1.2500000111758709

    [shell.launcher.providers.session]
    global = true

    [shell.panel]
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"

    [shell.shadow]
    direction = "down_right"

[system.monitor]
gpu_poll_seconds = 0

[theme]
builtin = "Ayu"
community_palette = "Oasis Abyss"
custom_palette = "Ayu"
mode = "dark"
source = "community"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ "zathura" ]

[wallpaper]
directory = "/home/browser/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.last]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.monitors.DP-1]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [wallpaper.monitors.DP-5]
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"

    [[wallpaper.favorite]]
    community_palette = "Oasis Abyss"
    palette_source = "community"
    path = "/home/browser/Pictures/Wallpapers/wallhaven-57d3e7_2560x1440.png"
    theme_mode = "light"

[widget.batt_headphones]
device = "/org/freedesktop/UPower/devices/headset_dev_AC_80_0A_AE_7D_10"
display_mode = "graphic"
type = "battery"

[widget.battery]
device = "/org/freedesktop/UPower/devices/battery_hidpp_battery_0"
display_mode = "graphic"
hide_when_full = true
hide_when_plugged = true

[widget.clock]
anchor = true
color = "on_surface_variant"

[widget.cpu_temp]
gauge_color = "secondary"
stat = "cpu_temp"
type = "sysmon"

[widget.cpu_usage]
type = "sysmon"

[widget.date]
color = "on_surface_variant"

[widget.gpu_temp]
stat = "gpu_temp"
type = "sysmon"

[widget.gpu_usage]
stat = "gpu_usage"
type = "sysmon"

[widget.headphone_batt]
device = "/org/freedesktop/UPower/devices/headset_dev_AC_80_0A_AE_7D_10"
display_mode = "graphic"
type = "battery"

[widget.hello]
type = "me/icue-presets:hello"

[widget.media]
hide_when_no_media = true

[widget.memory]
stat = "ram_used"
type = "sysmon"

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"